### ISSUE TITLE
HR percent in range -1 to 1

### ISSUE THREAD

**Issue by Honzackcz** [200Tigersbloxed/HRtoVRChat_OSC#12]
Will be nice to have option for HRPercent or new parameter, so there will be HR percentage float with range mapped to values -1 to 1 for better value accuracy in VRC. Some others VRC OSC HR apps have it.

**Comment by 200Tigersbloxed** [comment]
Changing the `minHR` and `maxHR` config values can increase/decrease accuracy, is there a specific reason to range `HRPercent` from -1 to 1?

**Comment by Honzackcz** [comment]
I know I can use min/max in a way. The reason is that it's easier to animate displays with float then int, with range -1 to 1 I can use full 0 - 255 bpms without loosing acurracy. I already use other app with that setup and it works nice.

**Comment by 200Tigersbloxed** [comment]
Implemented in [v2.2.0](https://github.com/200Tigersbloxed/HRtoVRChat_OSC/commit/761a5e78fb9f685b62e2e4b02b4b8bae180e199b)
