### ISSUE TITLE
Current Avatar Bug

### ISSUE THREAD

**Issue by LilyKemp** [200Tigersbloxed/HRtoVRChat_OSC#16]
Context: First time setting up HR to an avatar, I am using PulsoidSocket. The avatar in question had been previously named differently but had been updated with name/parameter changes while keeping the same id.

Current Avatar section of Incoming Data is not correct. The name and parameters of the current avatar are showing as the original name and parameters from before the name/parameters were changed.
This meant that there was no HR parameter in the parameters of the Current Avatar section even though it exists when checking the debug tools in VRC for that avatar, and therefore the numbers were not updating within VRC.

To get around this I just detached the avatar from my original blueprint ID and reuploaded it and it worked. 

Not sure if this is an HRtoVRChat bug or a bug on the end of the VRChat OSC data.

**Comment by 200Tigersbloxed** [comment]
This is not a bug. This is a VRChat issue where the OSC Config is not reloaded correctly, whereas the fix is to reset the OSC config.
