### ISSUE TITLE
Script cannot be loaded

### ISSUE THREAD

**Issue by CJBoom77** [200Tigersbloxed/HRtoVRChat_OSC#18]
I'm using the current version of the SDK. When I imported the project, it is supposed to show the root and fx link page, but instead, it shows this error. "The associated script can not be loaded. Please fix any compile errors and assign a valid script. Is this something I can fix or is this out of date? Thank you for the help.

**Comment by 200Tigersbloxed** [comment]
What does the error say? There should be more information provided in the Console Window. Are you also using VCC?

**Comment by CJBoom77** [comment]
> What does the error say? There should be more information provided in the Console Window. Are you also using VCC?

Yes, I am using the VRC Creator Companion. Here is the error in the console:

VRCBuildPipelineCallbacks failed to load a type in assembly 'VRC.SDKBase.Editor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. If this is Assembly-CSharp it's just Unity being in the middle of loading.
UnityEngine.Debug:LogWarning (object)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:Initialize ()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadMethodAttributes ()

**Comment by 200Tigersbloxed** [comment]
> Yes, I am using the VRC Creator Companion

The VCC is currently unsupported and may cause problems. I would recommend using the Unity Package Manager to import the VRCSDK instead.

https://twitter.com/Benaclejames/status/1625570122738896926
