### ISSUE TITLE
Extend pulse time of ''isHRBeat''

### ISSUE THREAD

**Issue by StreamArcaDad** [200Tigersbloxed/HRtoVRChat_OSC#19]
Hi there. Im trying to make a single sound of a custom heart beat to match the tempo my IRL heartbeat using isHRBeat. Sadly, the sound I am using is slightly longer than the bool pulse isHRBeat is sending. Ive trying using ''Has Exit time'' but the layer doesnt reset fast enought and it only ends up working every 8 to 10 actual pulse. Any solution in the scrip I could do or alternative?

**Comment by 200Tigersbloxed** [comment]
> Sadly, the sound I am using is slightly longer than the bool pulse isHRBeat is sending.

I think the better solution is just using a shorter audio. Out of the numerous people who have set up a system like this, I have heard no complaints about the time required.

The honest solution is support for Trigger animator types over OSC, but obviously, that is out of my scope.
