### ISSUE TITLE
isHRConnected not enabling

### ISSUE THREAD

**Issue by untuned** [200Tigersbloxed/HRtoVRChat_OSC#2]
The bool doesn't change from false to true.

![](https://untnd.me/L_eSGyNC1)

**Comment by 200Tigersbloxed** [comment]
What is your `hrType`?

**Comment by untuned** [comment]
> What is your `hrType`?

`hyperate`

**Comment by 200Tigersbloxed** [comment]
Here's where the issue would be

https://github.com/200Tigersbloxed/HRtoVRChat_OSC/blob/main/HRtoVRChat_OSC/HRManagers/HypeRateManager.cs#L11

However, unless I got the nullable incorrect, then I don't know why it would return false.

**Comment by untuned** [comment]
At the same time, `isHRBeat` doesn't... well... beat.

**Comment by 200Tigersbloxed** [comment]
It won't if the device isn't connected, so that's normal.

**Comment by 200Tigersbloxed** [comment]
Fixed in [v1.1.0](https://github.com/200Tigersbloxed/HRtoVRChat_OSC/releases/tag/v1.1.0)
