### ISSUE TITLE
Calculation mistake in the ParamsManager -> targetFloat variable

### ISSUE THREAD

**Issue by AndyK84** [200Tigersbloxed/HRtoVRChat_OSC#5]
There is a slight error in the calculation for the targetFloat.
It should be like this:
targetFloat = (HR - minhr) / (maxhr - minhr);

Currently it is this:
targetFloat = (HR - minhr) / maxhr;

**Comment by 200Tigersbloxed** [comment]
I see the calculation error! Thank you for pointing that out. I'll push this along with the new Prefab Updates!
